filetype off
silent! ruby require('rubygems')
call pathogen#runtime_append_all_bundles() 

set nocompatible                  " Must come first because it changes other options.

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

"set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs
set smarttab
set autoindent

" Break lines intelligently when wrapping
set linebreak
set display+=lastline

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

colorscheme zenburn 
set guicursor=i:block,n:blinkon0

let g:bufExplorerShowRelativePath=1

let mapleader = ","
set listchars=tab:>-,trail:·,eol:$
set shortmess=atI

imap jk <Esc>
nmap <c-tab> <c-w>w

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

if has('gui_running')
  set columns=80
  set lines=50
  
  set guifont=Consolas:h15
  set guioptions-=T               "kill toolbar
  set guioptions-=m               "kill menu
  set guioptions-=r               "kill right scrollbar
  set guioptions-=l               "kill left scrollbar
  set guioptions-=L               "kill left scrollbar with multiple buffers
endif

" Autocmds
au FileType make     set noexpandtab

function! Coding()
  syn match OverLength /^.\{80\}.*$/ 
  hi OverLength ctermbg=red ctermfg=white guifg=#e182ed

  syn match ExtraWhitespace /\s\+$\| \+\ze\t/
  hi ExtraWhitespace ctermbg=darkgreen guibg=darkgreen

  setl cursorline
  hi cursorline guibg=#313633
endfunction

au FileType ruby call Coding()
au BufRead,BufNewFile *.txt set filetype=mkd
